name: Manual Trigger Workflow

on:
  # manual dispatch
  workflow_dispatch:
    # dispatch when tere is an issue
  issues:
    types: [opened]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Step 1 complete!"
      - name: Step 2
        run: echo "Step 2 complete!"
        # custom variables that will be available in the run script.
        env:
          VARIABLE_NAME: value

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Cowsays
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: "Ready for prod–ship it!"
          color: magenta